collated: true;
context:
  label: Lemmik värv
  namie: nimi
  placeholder: Vali
  helpText: Siit saad valida
  options:
    option1: value1
    option2: value2
    option3: value3
    option4: value4
    option5: value5
    option6: value6

variants:
  - name: inline
    context:
      modifiers: select--inline
  - name: error
    label: Valideerimine
    context:
      modifiers: is-error