label: Vihjemullid
collated: true
display:
  height: 400px;
context:
  tooltipText: Vihjemulli tekst
variants:
  - name: html
    label: Pikad vihjed
    notes: Pikad vihjed v천imaldavad k체ll kuvada rohkem teksti, kuid siiski tuleks piirduda paari lausega. Nende eesm채rk on anda kasutajale kiiret lisainfot kohtades, kuhu seda poleks muidu v천imalik lisada.
