label: Tsitaadid
notes: Tsitaat Lab Grotesque Regular 33px.
context:
  content: Electrical science has revealed to us the true nature of light, has provided us with innumerable appliances and instruments of precision, and has thereby vastly added to the exactness of our knowledge.
  autor: Nikola Tesla
