context:
  icons:
    - ambulance
    - chevron-right
    - chevron-left
    - chevron-up
    - chevron-down
    - info-circle
    - phone
    - users
    - newspaper
    - map
    - sitemap
    - lock
    - search
    - check
    - plane
    - shopping-cart