label: Rippmenüü
collated: true
display:
  min-height: 250px
context:
  id: dropdown-menu
  text: Menüü
  menu:
    - text: Menüü pelakiiri
      link: https://www.tallinn.ee
    - text: Teine menüü pealkiiri
    - text: Menüü pelakiiri

variants:
  - name: open
    label: Avatud
    context:
      dropdown-modifiers: is-active